name: universal_echarts
description: A new Flutter project.
version: 1.0.0+1
homepage: https://github.com/AgamottoZ/universal_echarts
repository: https://github.com/AgamottoZ/universal_echarts
maintainer: Bach Mai (@nogicoder)
flutter:
  plugin:
    platforms:
      android:
        pluginClass: UniversalCharts
      ios:
        pluginClass: UniversalCharts
      web:
        pluginClass: UniversalCharts

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_echarts: ^2.0.0
  flutter_markdown: ^0.6.1
  markdown: ^4.0.0
  html2md: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter